(function(){
var g=false,h=null,l=true,m=(new Date).getTime();var aa={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",
google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ba={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},ca={google_only_pyv_ads:"pyv"};function da(a){return aa[a]||ba[a]||ca[a]||h};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);function o(){this.b=this.p();this.h=g;if(!this.b)this.h=this.j()}o.prototype.f="__gads=";o.prototype.c="GoogleAdServingTest=";o.prototype.o=function(){return this.b};o.prototype.setCookieInfo=function(a){this.a=a._cookies_[0];if(this.a!=h){this.b=this.a._value_;this.q()}};o.prototype.l=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
o.prototype.k=function(a){if(!(this.b!=h||!this.h)){var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+ea(a)+"&domain="+ea(c);document.write("<"+b+' src="'+d+'"></'+b+">")}};o.prototype.j=function(){document.cookie=this.c+"Good";var a=this.g(this.c),b=a=="Good";if(b){var c=this.l(-1);document.cookie=this.c+"; expires="+c.toGMTString()}return b};o.prototype.p=function(){var a=this.g(this.f);return a};
o.prototype.g=function(a){var b=document.cookie,c=b.indexOf(a),d=h;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};o.prototype.q=function(){if(!(this.a==h))if(!(this.b==h)){var a=new Date;a.setTime(1000*this.a._expires_);var b=this.a._domain_,c=this.f+this.b+"; expires="+a.toGMTString()+"; path="+this.a._path_+"; domain=."+b;document.cookie=c}};function q(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function fa(a,b){if(a=="true")return l;if(a=="false")return g;return b}
function ga(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;for(;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=h}return b.toString()}else if(ha("msie")&&!window.opera){var c=h;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=h){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var ia=ia||{},r=this,s=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]")return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};var ja=function(a){var b=s(a);return b=="array"||b=="object"&&typeof a.length=="number"};
var ka=function(a){var b=s(a);return b=="object"||b=="array"||b=="function"},la=function(a){var b=s(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=la(a[d]);return c}return a};var ma=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=typeof a=="string"?a.split(""):a,f=0;for(;f<d;f++)f in e&&b.call(c,e[f],f,a)}},na=function(a){if(s(a)=="array")return a.concat();else{var b=[],c=0,d=a.length;for(;c<d;c++)b[c]=a[c];return b}};var t=function(a,b){this.x=typeof a!="undefined"?a:0;this.y=typeof b!="undefined"?b:0};t.prototype.clone=function(){return new t(this.x,this.y)};t.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var w=function(a,b){this.width=a;this.height=b};w.prototype.clone=function(){return new w(this.width,this.height)};w.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};w.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};w.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
w.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};w.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var sa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var ta=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},za=function(a,b){if(b)return a.replace(ua,"&amp;").replace(va,"&lt;").replace(wa,"&gt;").replace(xa,"&quot;");else{if(!ya.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(ua,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(va,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(wa,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(xa,"&quot;");return a}},ua=/&/g,va=/</g,wa=/>/g,xa=/\"/g,ya=/[&<>\"]/,Aa=function(a,b){var c=b.length,d=0;for(;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};
var x=function(a,b){var c=0,d=ta(String(a)).split("."),e=ta(String(b)).split("."),f=Math.max(d.length,e.length),i=0;for(;c==0&&i<f;i++){var j=d[i]||"",n=e[i]||"",k=new RegExp("(\\d*)(\\D*)","g"),u=new RegExp("(\\d*)(\\D*)","g");do{var v=k.exec(j)||["","",""],p=u.exec(n)||["","",""];if(v[0].length==0&&p[0].length==0)break;var D=v[1].length==0?0:parseInt(v[1],10),T=p[1].length==0?0:parseInt(p[1],10);c=Ba(D,T)||Ba(v[2].length==0,p[2].length==0)||Ba(v[2],p[2])}while(c==0)}return c},Ba=function(a,b){if(a<
b)return-1;else if(a>b)return 1;return 0};var y,Ca,z,Da,Ea,Fa,Ga,Ha,Ia,Ja=function(){return r.navigator?r.navigator.userAgent:h};var Ka=function(){Fa=Ea=Da=z=Ca=y=g;var a;if(a=Ja()){var b=r.navigator;y=a.indexOf("Opera")==0;Ca=!y&&a.indexOf("MSIE")!=-1;Da=(z=!y&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Fa=(Ea=!y&&!z&&b.product=="Gecko")&&b.vendor=="Camino"}};Ka();
var A=y,B=Ca,La=Ea,C=z,Ma=Da,Na=function(){var a=r.navigator;return a&&a.platform||""},Oa=Na(),Pa=function(){Ga=Oa.indexOf("Mac")!=-1;Ha=Oa.indexOf("Win")!=-1;Ia=Oa.indexOf("Linux")!=-1};Pa();var Qa=Ia,Ra=function(){var a="",b;if(A&&r.opera){var c=r.opera.version;a=typeof c=="function"?c():c}else{if(La)b=/rv\:([^\);]+)(\)|;)/;else if(B)b=/MSIE\s+([^\);]+)(\)|;)/;else if(C)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Ja());a=d?d[1]:""}}return a},E=Ra();var F;var Sa=function(a){return a?new G(H(a)):F||(F=new G)};
var Ta=function(a){return typeof a=="string"?document.getElementById(a):a},I=Ta,Va=function(a,b){sa(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Ua)a.setAttribute(Ua[d],c);else a[d]=c})},Ua={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},Wa=function(a){var b=a||r||window,c=b.document;
if(C&&!(x(E,"500")>=0)&&!Ma){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new w(b.innerWidth,d)}var f=Sa(c),i=f.e()&&(!A||A&&x(E,"9.50")>=0)?c.documentElement:c.body;return new w(i.clientWidth,i.clientHeight)},Xa=function(){var a=F||(F=new G);return a.i.apply(a,arguments)},Ya=function(a,b){a.appendChild(b)},J=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):h},Za=function(a,b){var c=b.parentNode;
c&&c.replaceChild(a,b)};
var bb=C&&x(E,"521")<=0,cb=function(a,b){if(typeof a.contains!="undefined"&&!bb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},H=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},db=function(a){if(a&&typeof a.length=="number")if(ka(a))return typeof a.item=="function"||typeof a.item=="string";else if(s(a)=="function")return typeof a.item=="function";
return g},G=function(a){this.d=a||r.document||document};
G.prototype.i=function(a,b){if(B&&b&&(b.name||b.type)){var c=["<",a];b.name&&c.push(' name="',za(b.name),'"');if(b.type){c.push(' type="',za(b.type),'"');b=la(b);delete b.type}c.push(">");a=c.join("")}var d=this.createElement(a);b&&Va(d,b);if(arguments.length>2){function e(j){if(j)this.appendChild(d,typeof j=="string"?this.createTextNode(j):j)}var f=2;for(;f<arguments.length;f++){var i=arguments[f];ja(i)&&!(ka(i)&&i.nodeType>0)?ma(db(i)?na(i):i,e,this):e.call(this,i)}}return d};
G.prototype.createElement=function(a){return this.d.createElement(a)};G.prototype.createTextNode=function(a){return this.d.createTextNode(a)};G.prototype.e=function(){var a=this.d;if(a.compatMode)return a.compatMode=="CSS1Compat";if(C){var b=a.createElement("div");b.style.cssText="position:absolute;width:0;height:0;width:1";var c=b.style.width=="1px"?"BackCompat":"CSS1Compat";return(a.compatMode=c)=="CSS1Compat"}return g};
G.prototype.n=function(){var a=this.d;return!C&&this.e()?a.documentElement:a.body};G.prototype.m=function(){var a=this.n();return new t(a.scrollLeft,a.scrollTop)};G.prototype.appendChild=Ya;G.prototype.removeNode=J;G.prototype.replaceNode=Za;G.prototype.contains=cb;var eb,fb,gb,hb,ib,jb,kb=function(){jb=ib=hb=gb=fb=eb=g;var a=Ja();if(!!a)if(a.indexOf("Firefox")!=-1)eb=l;else if(a.indexOf("Camino")!=-1)fb=l;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)gb=l;else if(a.indexOf("Android")!=-1)hb=l;else if(a.indexOf("Chrome")!=-1)ib=l;else if(a.indexOf("Safari")!=-1)jb=l};kb();var lb=fb;var mb,nb=function(a,b){var c=H(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return h};var K=function(a,b){return nb(a,b)||(a.currentStyle?a.currentStyle[b]:h)||a.style[b]};
var ob=function(a){var b;b=a?a.nodeType==9?a:H(a):document;if(B&&!Sa(b).e())return b.body;return b.documentElement},pb=function(a){var b=a.getBoundingClientRect();if(B){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=c.documentElement.clientTop+c.body.clientTop}return b},qb=function(a){if(B)return a.offsetParent;var b=H(a),c=K(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;for(;e&&e!=b;e=e.parentNode){c=K(e,"position");d=d&&c=="static"&&e!=b.documentElement&&
e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return h},rb=function(a){var b,c=H(a),d=K(a,"position"),e=La&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0);if(typeof mb=="undefined")mb=lb&&!(x(E,"1.8.0.11")>=0);var f=new t(0,0),i=ob(c);if(a==i)return f;if(a.getBoundingClientRect){b=pb(a);var j=Sa(c).m();f.x=b.left+j.x;f.y=b.top+j.y}else if(c.getBoxObjectFor&&!e&&!mb){b=
c.getBoxObjectFor(a);var n=c.getBoxObjectFor(i);f.x=b.screenX-n.screenX;f.y=b.screenY-n.screenY}else{var k=a;do{f.x+=k.offsetLeft;f.y+=k.offsetTop;if(k!=a){f.x+=k.clientLeft||0;f.y+=k.clientTop||0}if(C&&K(k,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}k=k.offsetParent}while(k&&k!=a);if(A||C&&d=="absolute")f.y-=c.body.offsetTop;k=a;for(;(k=qb(k))&&k!=c.body;){f.x-=k.scrollLeft;if(!A||k.tagName!="TR")f.y-=k.scrollTop}}return f},sb=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,
10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;var i=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return i}},tb=function(a){var b=H(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=K(a,"fontFamily");if(A&&Qa)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Aa(c,"\"'")},ub=function(a){var b=a.match(/[^\d]+$/);return b&&b[0]||h},vb={cm:1,"in":1,mm:1,
pc:1,pt:1},wb={em:1,ex:1},xb=function(a){var b=K(a,"fontSize"),c=ub(b);if(b&&"px"==c)return parseInt(b,10);if(B)if(c in vb)return sb(a,b,"left","pixelLeft");else if(a.parentNode&&c in wb)return sb(a.parentNode,b,"left","pixelLeft");var d=Xa("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});Ya(a,d);b=d.offsetHeight;J(d);return b};var L=document,N=navigator,O=window;
function yb(){var a=L.cookie,b=Math.round((new Date).getTime()/1000),c=O.google_analytics_domain_name,d=typeof c=="undefined"?zb("auto"):zb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,i=a.indexOf("__utmc="+d)>-1,j,n={};if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");n.sid=f&&i?j[3]+"":O&&O.gaGlobal&&O.gaGlobal.sid?O.gaGlobal.sid:b+"";n.vid=j[0]+"."+j[1];n.from_cookie=l}else{n.sid=O&&O.gaGlobal&&O.gaGlobal.sid?O.gaGlobal.sid:b+"";n.vid=O&&O.gaGlobal&&O.gaGlobal.vid?
O.gaGlobal.vid:(Ab()^Bb()&2147483647)+"."+b;n.from_cookie=g}n.dh=d;n.hid=O&&O.gaGlobal&&O.gaGlobal.hid?O.gaGlobal.hid:Ab();return O.gaGlobal=n}function Ab(){return Math.round(Math.random()*2147483647)}
function Bb(){var a=L.cookie?L.cookie:"",b=O.history.length,c,d,e=[N.appName,N.version,N.language?N.language:N.browserLanguage,N.platform,N.userAgent,N.javaEnabled()?1:0].join("");if(O.screen)e+=O.screen.width+"x"+O.screen.height+O.screen.colorDepth;else if(O.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=L.referrer?L.referrer:"";c=e.length;for(;b>0;)e+=b--^c++;return Cb(e)}
function Cb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;d=a.length-1;for(;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function zb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=L.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Cb(a.toLowerCase())};var P="",Db=l;function Q(a){if(a){if(P!="")P+=",";P+=a}}var Eb=g,Fb=fa("true",g);function R(a){return a!=h?'"'+a+'"':'""'}function ea(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function S(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function U(a){var b=window,c=da(a),d=b[a];S(c,d)}function V(a,b){b!=h&&S(a,ea(b))}function W(a){var b=window,c=da(a),d=b[a];V(c,d)}
function X(a,b){var c=window,d=da(a),e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];S(d,e)}function Gb(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){S("u_h",b.height);S("u_w",b.width);S("u_ah",b.availHeight);S("u_aw",b.availWidth);S("u_cd",b.colorDepth)}S("u_tz",d);S("u_his",history.length);S("u_java",c);navigator.plugins&&S("u_nplug",navigator.plugins.length);navigator.mimeTypes&&S("u_nmime",navigator.mimeTypes.length)}
function Hb(a){if(!!a.google_enable_first_party_cookie){if(a._GA_googleCookieHelper==h)a._GA_googleCookieHelper=new o;if(!a._google_cookie_fetched){a._google_cookie_fetched=l;a._GA_googleCookieHelper.k(Ib(a.google_ad_client))}}}function Ib(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Jb(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}function Kb(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Lb(){var a=Math.random(),b=q("0",0.03),c=2*b;if(a<b)return"30143019";if(a<c)return"30143020";return""}function Mb(){var a=Math.random(),b=q("0",0.03),c=2*b;if(a<b)return"30143021";if(a<c)return"30143022";return""}function Nb(){var a=Math.random(),b=q("0.03",0.02),c=2*b;if(a<b)return"6083028";if(a<c)return"6083029";return""}
function Ob(){var a=Math.random(),b=q("0.02",0.0050),c=2*b;if(a<b)return"54341001";if(a<c)return"54341002";return""}function Pb(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}
function Qb(a,b,c,d){var e=Kb(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+R(Y(c))+"></"+f+">");else if(a.google_ad_output=="html")if(Rb(a)&&typeof ExpandableAdSlotFactory=="function"&&typeof ExpandableAdSlotFactory.createIframe=="function"){var i=a.google_container_id||d||h;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+
e,Y(c),a.google_ad_width,a.google_ad_height,i)}else{var j='<iframe name="google_ads_frame" width='+R(a.google_ad_width)+" height="+R(a.google_ad_height)+" frameborder="+R(a.google_ad_frameborder)+" src="+R(Y(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';j=Sb(a.google_ad_width,a.google_ad_height,j);a.google_container_id?Tb(a.google_container_id,b,j):b.write(j)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+
R(Y(c))+"></"+f+">")}function Rb(a){if(!Eb)return g;var b=P.indexOf("30143020")!=-1,c=P.indexOf("30143019")!=-1,d=a.google_expandable_iframe;return Fb&&!c||b||d}function Ub(a){var b=fa("false",g);return b&&a.indexOf("30143021")==-1||a.indexOf("30143022")!=-1}
function Sb(a,b,c){var d=Ub(P);if(Eb&&d){var e="border:none;height:"+b+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+a+"px";return'<ins style="display:inline-table;'+e+'"><ins style="display:block;'+e+'">'+c+"</ins></ins>"}return c}function Vb(a,b,c){if(!a)return g;if(!b)return l;if(!c)return g;var d=Ob();Q(d);return d=="54341002"}
function Wb(a){for(var b in aa)a[b]=h;for(var b in ba)b=="google_correlator"||(a[b]=h);for(var b in ca)a[b]=h;a.google_allow_expandable_ads=h;a.google_container_id=h;a.google_expandable_iframe=h;a.google_tag_info=h}function Xb(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function Z(a){return a&&a.indexOf("_sdo")!=-1}
function Yb(a){var b=h,c=window,d=document,e=m,f=c.google_ad_format,i=Zb(c),j;if(c.google_cpa_choice!=b){c.google_ad_url=i+"/cpa/ads?";j=escape(Ib(c.google_ad_client));c.google_ad_region="_google_cpa_region_";U("google_cpa_choice");if(typeof d.characterSet!="undefined")V("oe",d.characterSet);else typeof d.charset!="undefined"&&V("oe",d.charset)}else if(Z(f)){c.google_ad_url=i+"/pagead/sdo?";j=escape(Jb(c.google_ad_client))}else{c.google_ad_url=i+"/pagead/ads?";j=escape(Ib(c.google_ad_client))}c.google_ad_url+=
"client="+j;U("google_ad_host");U("google_ad_host_tier_id");var n=c.google_num_slots_by_client,k=c.google_num_slots_by_channel,u=c.google_prev_ad_formats_by_region,v=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var p=c.google_ad_region==b?"":c.google_ad_region;if(Z(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if(Xb(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){u[p]=b;v[p]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&p=="")return g}S("dt",m);U("google_language");c.google_country?U("google_country"):U("google_gl");U("google_region");
W("google_city");W("google_hints");U("google_safe");U("google_encoding");U("google_last_modified_time");W("google_alternate_ad_url");U("google_alternate_color");U("google_skip");U("google_targeting");var D=c.google_ad_client;if(n[D])n[D]+=1;else{n[D]=1;n.length+=1}if(u[p])if(!Z(f)){V("prev_fmts",u[p].toLowerCase());n.length>1&&S("slot",n[D])}v[p]&&V("prev_slotnames",v[p].toLowerCase());if(Vb(f,c.google_ad_slot,Db)){V("format",f.toLowerCase());Z(f)||(u[p]=u[p]?u[p]+","+f:f)}else if(c.google_ad_slot)v[p]=
v[p]?v[p]+","+c.google_ad_slot:c.google_ad_slot;U("google_max_num_ads");S("output",c.google_ad_output);U("google_adtest");U("google_ad_callback");U("google_ad_slot");W("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&S("dblk",1);if(c.google_ad_channel){W("google_ad_channel");var T="",$a=c.google_ad_channel.split($b),oa=0;for(;oa<$a.length;oa++){var pa=$a[oa];if(k[pa])T+=pa+"+";else k[pa]=1}V("pv_ch",T)}if(c.google_ad_host_channel){W("google_ad_host_channel");var hc=
ac(c.google_ad_host_channel,c.google_viewed_host_channels);V("pv_h_ch",hc)}c.google_enable_first_party_cookie&&V("cookie",c._GA_googleCookieHelper.o());W("google_page_url");X("google_color_bg",e);X("google_color_text",e);X("google_color_link",e);X("google_color_url",e);X("google_color_border",e);X("google_color_line",e);c.google_reuse_colors?S("reuse_colors",1):S("reuse_colors",0);U("google_font_face");U("google_kw_type");W("google_kw");W("google_contents");U("google_num_radlinks");U("google_max_radlink_len");
U("google_rl_filtering");U("google_rl_mode");U("google_rt");W("google_rl_dest_url");U("google_num_radlinks_per_unit");U("google_ad_type");U("google_image_size");U("google_ad_region");if(Eb)if(c.google_expandable_iframe===g)Pb(c);else if(j in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=l;else{if(!(c.google_expandable_iframe==l)){var M=Lb();Q(M);if(M=="30143019"||M==""&&!Fb)Pb(c);if(!M){M=Mb();Q(M)}}}else Pb(c);
V("eid",P);var ab=c.google_allow_expandable_ads;if(ab!=h)ab?S("ea","1"):S("ea","0");U("google_feedback");W("google_referrer_url");W("google_page_location");S("frm",c.google_iframing);U("google_bid");U("google_ctr_threshold");U("google_cust_age");U("google_cust_gender");U("google_cust_interests");U("google_cust_id");U("google_cust_job");U("google_cust_u_url");U("google_cust_l");U("google_cust_lh");U("google_cust_ch");U("google_ed");U("google_video_doc_id");U("google_video_product_type");W("google_ui_features");
W("google_ui_version");W("google_tag_info");W("google_only_ads_with_video");W("google_only_pyv_ads");W("google_disable_video_autoplay");if(a){V("ff",tb(a));V("fs",xb(a));var qa=rb(a),ra=Wa();if(qa&&ra){V("biw",ra.width);V("bih",ra.height);V("adx",qa.x);V("ady",qa.y)}}yb();S("ga_vid",c.gaGlobal.vid);S("ga_sid",c.gaGlobal.sid);S("ga_hid",c.gaGlobal.hid);S("ga_fc",c.gaGlobal.from_cookie);W("google_analytics_uacct");U("google_ad_override");U("google_flash_version");Gb(c);return l}
function ac(a,b){var c=a.split("|"),d=-1,e=[],f=0;for(;f<c.length;f++){var i=c[f].split($b);b[f]||(b[f]={});var j="",n=0;for(;n<i.length;n++){var k=i[n];if(!(k==""))if(b[f][k])j+="+"+k;else b[f][k]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var u="";if(d>-1){var f=0;for(;f<d;f++)u+=e[f]+"|";u+=e[d]}return u}
function bc(){var a=window,b=document;Hb(a);var c=Nb();Q(c);var d;if(c=="6083029"){var e="google_temp_span";d=a.google_container_id&&I(a.google_container_id)||I(e);if(!d&&!a.google_container_id){b.write("<span id="+e+"></span>");d=I(e)}}var f=Yb(d);d&&d.id==e&&J(d);if(!!f){Qb(a,b,a.google_ad_url);Wb(a)}}function Y(a){var b=(new Date).getTime()-m,c="&dtd="+(b<1000?b:"M");return a+c}function cc(){bc();return l}
function dc(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return l}
function ec(a){var b=window,c=h,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(Z(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html"){b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;Db=g}fc(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=m;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ga();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function ha(a){if(a in gc)return gc[a];return gc[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var gc={};
function ic(a){var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;for(;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(i){}}return b}function jc(){var a=window,b=ic(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function kc(a,b){for(var c in b)a["google_"+c]=b[c]}
function lc(a,b){if(!b)return a.location;return a.referrer}function mc(a,b){if(!b&&a.google_referrer_url==h)return"0";else if(b&&a.google_referrer_url==h)return"1";else if(!b&&a.google_referrer_url!=h)return"2";else if(b&&a.google_referrer_url!=h)return"3";return"4"}function nc(a,b,c,d){a.page_url=lc(c,d);a.page_location=h}function oc(a,b,c,d){a.page_url=b.google_page_url;a.page_location=lc(c,d)||"EMPTY"}
function pc(a,b){var c={},d=dc(a,b);c.iframing=mc(a,d);!!a.google_page_url?oc(c,a,b,d):nc(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:h;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function qc(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=h;b.page_url=c;b.page_location=a.location;b.last_modified_time=h;b.referrer_url=c;return b}
function fc(a,b){var c;c=a.google_page_url==h&&rc[b.domain]?qc(b):pc(a,b);kc(a,c)}function Tb(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var rc={};rc["ad.yieldmanager.com"]=l;var $b=/[+, ]/;window.google_render_ad=bc;var sc={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function tc(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in sc;if(e.length>=2)f=f||e[e.length-2]in sc;return f}
function Zb(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!tc(a)&&a.google_new_domain_enabled==1)return b;return c};var uc={google_ad_height:"h",google_ad_width:"w",google_box_len:"box_len",google_button_pos:"btn_pos",google_link_target:"same_win",google_logo_pos:"logo",google_rs_pos:"rl_pos",google_ss_domains:"ss_dmns"};function vc(){window.google_ad_output="html"}function $(a){var b=window,c=uc[a]||h,d=b[a];S(c,d)}function wc(){$("google_box_len");$("google_link_target");$("google_logo_pos");$("google_button_pos");$("google_rs_pos");$("google_ss_domains");$("google_ad_width");$("google_ad_height");return l}
function xc(a){for(var b in uc)a[b]=h}function yc(){var a=window,b=document;Hb(a);var c;if(Math.random()<0.01){var d="google_temp_span";if(!I(d)){b.write("<span id="+d+"></span>");c=I(d)}}var e=Yb(c)&&wc();c&&J(c);if(!!e){Qb(a,b,a.google_ad_url);xc(a);Wb(a)}}jc();ec(cc);vc();yc();
})()
