# Gionee wangguojun 20170214 modify for DRV2604L start
obj-$(CONFIG_GN_BSP_MTK_VIBRATOR_DRV2604L) += gn_ti_drv2604l/


#obj-$(CONFIG_MTK_VIBRATOR) := vibrator_drv.o
#obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/

#ccflags-y += -I$(srctree)/drivers/misc/mediatek/vibrator/$(MTK_PLATFORM)

# Gionee wangguojun 20170214 modify for DRV2604L end
