#!/bin/bash
#===================================================================
# 此自动化编译脚本仅适用于android平台，且使用git版本控制软件的项目
# SCM ---- 刘小惠
#===================================================================
VERSION_NUMBER="2.3"
PROJECT_PATH=""
PRJO_PATH_TAG=0
PROJECT_NAME=""
function guide()
{
	if [[ -d "$HOME/bin"  && ! -e "$HOME/bin/repo" ]]; then
		export PATH=$PATH:$HOME/bin
		curl http://10.8.10.22/gnrepo > $HOME/bin/repo
	elif [ ! -d "$HOME/bin" ] ; then
		mkdir $HOME/bin 
		curl http://10.8.10.22/gnrepo > $HOME/bin/repo
	else
		echo "$HOME/bin已存在"
		curl http://10.8.10.22/gnrepo > $HOME/bin/repo
	fi
	result=$(grep 'export PATH=$PATH:$HOME/bin' $HOME/.bashrc)
	if [ -z "$result" ];then
		echo 'export PATH=$PATH:$HOME/bin' >> $HOME/.bashrc
		export PATH=$PATH:$HOME/bin
	fi
	chmod a+x $HOME/bin/repo
}

function repoinit()
{
	read -p "请輸入代码存放路径(必须写上全路径如""/home/ala/REPO_RES"":)默认为当前路径:" PROJECT_PATH
	read -p "请輸入项目名称(请输入大写):" PROJECT_NAME
	if [[ -d ${PROJECT_PATH} && ! -d ${PROJECT_PATH}/.repo ]];then
		pushd ${PROJECT_PATH} >/dev/null
		echo "repo init -u GerritServer:/manifest.git -m $PROJECT_NAME.xml" 
		$HOME/bin/repo init -u GerritServer:/manifest.git -m $PROJECT_NAME.xml
		popd >/dev/null
	elif [[ -d ${PROJECT_PATH} && -d ${PROJECT_PATH}/.repo ]];then
		echo "您指定目录已做过repo init,请指定新路径."
		PRJO_PATH_TAG=1
	else
		echo "repo init -u GerritServer:/manifest.git -m $PROJECT_NAME.xml" 
		$HOME/bin/repo init -u GerritServer:/manifest.git -m $PROJECT_NAME.xml
	fi
}

function copyReviewScript()

{
	while read pergit
	do
	pergit=$(echo ${pergit}|awk -F "/.git" '{printf("%s",$1)}')
	echo ${pergit}
	pushd ${pergit} >~/null
	pwd
	local username=$(git config user.email|awk -F "@gionee.com" '{printf("%s",$1)}')
	echo "username:${username}"	
	gitdir=$(git rev-parse --git-dir); scp -r -p -P 29418 ${username}@10.8.10.19:hooks/ ${gitdir}
	popd >~/null
	done < <( find . -path "*.repo" -prune -o -name .git -print )
}

function main()
{
	echo "当前脚本版本号为：$VERSION_NUMBER"
	guide
	repoinit
	while [ "$PRJO_PATH_TAG" -eq 1 ]
	do
		PRJO_PATH_TAG=0
		repoinit
	done
	echo "repo sync" 
	$HOME/bin/repo sync
	#拷贝review脚本
	copyReviewScript
}

main
