######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 5 15:20:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp

RESOURCES +=
