(function(){var f=true,g=null,j=false,k=this,aa=function(a,b,c){a=a.split(".");c=c||k;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}},ba=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};Math.floor(Math.random()*2147483648).toString(36);
var m=function(a,b){var c=b||k;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},o=function(a,b,c){aa(a,b,c)},p=function(a,b,c){a[b]=c},q=function(a,b){function c(){}c.prototype=b.prototype;a.Ca=b.prototype;a.prototype=new c};var r=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},ca=function(a,b){if(a=="true")return f;if(a=="false")return j;return b},da=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,s=function(a,b){if(!a)return b;var c=a.match(da);return c?c[0]:b};var fa=function(){return s("","pagead2.googlesyndication.com")};var ia=function(a){if(a.indexOf("&")!=-1)return"document"in k&&a.indexOf("<")==-1?ga(a):ha(a);return a},ga=function(a){var b=k.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},ha=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},
ka=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(d.length,e.length),i=0;c==0&&i<h;i++){var l=d[i]||"",n=e[i]||"",G=RegExp("(\\d*)(\\D*)","g"),z=RegExp("(\\d*)(\\D*)","g");do{var A=G.exec(l)||["","",""],B=z.exec(n)||["","",""];if(A[0].length==0&&B[0].length==0)break;c=A[1].length==0?0:parseInt(A[1],10);var ea=B[1].length==0?0:parseInt(B[1],10);c=ja(c,ea)||ja(A[2].length==0,B[2].length==0)||
ja(A[2],B[2])}while(c==0)}return c},ja=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var t=function(a,b){this.width=a;this.height=b};t.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};t.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var u,la,ma,na,oa,pa,qa,ra,sa,ta=function(){return k.navigator?k.navigator.userAgent:g},ua=function(){return k.navigator},va=function(){oa=na=ma=la=u=j;var a;if(a=ta()){var b=ua();u=a.indexOf("Opera")==0;la=!u&&a.indexOf("MSIE")!=-1;na=(ma=!u&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;oa=!u&&!ma&&b.product=="Gecko"}};va();
var wa=u,xa=la,ya=oa,za=ma,Aa=na,Ba=function(){var a=ua();return a&&a.platform||""},Ca=Ba(),Da=function(){pa=Ca.indexOf("Mac")!=-1;qa=Ca.indexOf("Win")!=-1;ra=Ca.indexOf("Linux")!=-1;sa=!!ua()&&(ua().appVersion||"").indexOf("X11")!=-1};Da();var Ea=function(){var a="",b;if(wa&&k.opera){a=k.opera.version;a=typeof a=="function"?a():a}else{if(ya)b=/rv\:([^\);]+)(\)|;)/;else if(xa)b=/MSIE\s+([^\);]+)(\)|;)/;else if(za)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(ta()))?a[1]:""}return a},Fa=Ea(),Ga={};var Ha=function(a){var b=a.document;if(za&&!(Ga["500"]||(Ga["500"]=ka(Fa,"500")>=0))&&!Aa){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new t(a.innerWidth,b)}a=b.compatMode=="CSS1Compat";if(wa&&!(Ga["9.50"]||(Ga["9.50"]=ka(Fa,"9.50")>=0)))a=j;a=a?b.documentElement:b.body;return new t(a.clientWidth,a.clientHeight)};var v=document,w=window,Ia=function(a){var b=g;if((a=a.getElementsByTagName("script"))&&a.length){b=a[a.length-1];b=b.parentNode}return b};Ia(v);var Ja="http://"+fa()+"/pagead/show_ads.js";function x(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function Ka(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return j;window.setTimeout(function(){e.appendChild(d)},0);return f}
function La(a,b){if(a.attachEvent){a.attachEvent("onload",b);return f}if(a.addEventListener){a.addEventListener("load",b,j);return f}return j}var Ma=function(a){if(!("google_onload_fired"in a)){a.google_onload_fired=j;La(a,function(){a.google_onload_fired=f})}};function Na(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}function y(a){if(a in Oa)return Oa[a];return Oa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var Oa={};
function Pa(){return y("msie")&&!window.opera}
function Qa(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a.toString()}else if(Pa()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
a=6;b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(h){}}if(b){a=b.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function Ra(a,b){if(!(Math.random()<1.0E-4)){var c=Math.random();if(c<b){c=Math.floor(c/b*a.length);return a[c]}}return""}
var Sa=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},Ta=function(a,b){var c=b||w;if(a&&c.top!=c)c=c.top;try{return c.document&&!c.document.body?new t(-1,
-1):Ha(c||window)}catch(d){return new t(-12245933,-12245933)}},Ua=function(a,b){var c=a.length;if(c==0)return 0;for(var d=b||305419896,e=0;e<c;e++){var h=a.charCodeAt(e);d^=(d<<5)+(d>>2)+h&4294967295}return d>0?d:4294967296+d},Va=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=f;a=Ta(!c,a);b.push(a.width.toString());b.push(a.height.toString());return Ua(b.join(""))},Wa=function(a){if(!a)return"";var b=[],c=0;for(a=a;a&&c<25;a=a.parentNode,++c)b.push(a.id||
"");return b.join()},Xa=function(a){try{return!!a.document}catch(b){return j}};var Ya=r("0.005",0),Za=r("0.01",0),$a=r("0.001",0),ab=r("0.006",0),bb=r("0.008",0);var cb=ca("false",j),db=ca("false",j),eb=ca("false",j),fb=ca("false",j);var gb=function(a,b,c){b=m(b,k,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";if(d.fileName)e=d.fileName;var h=-1;if(d.lineNumber)h=d.lineNumber;b=b(c,e,h);if(!b)throw d;}window.onerror=a};o("google_protectAndRun",gb);
var ib=function(a,b,c,d){if(Math.random()<0.01){var e=v;a=["http://",s("","pagead2.googlesyndication.com"),"/pagead/gen_204","?id=jserror","&jscb=",cb?1:0,"&jscd=",db?1:0,"&context=",x(a),"&msg=",x(b),"&file=",x(c),"&line=",x(d.toString()),"&url=",x(e.URL.substring(0,512)),"&ref=",x(e.referrer.substring(0,512))];a.push(hb());Na(w,a.join(""))}return!eb};o("google_handleError",ib);
var hb=function(){var a=["&client=",x(w.google_ad_client),"&format=",x(w.google_ad_format),"&slotname=",x(w.google_ad_slot),"&output=",x(w.google_ad_output),"&ad_type=",x(w.google_ad_type)];return a.join("")};var C=function(){this.ba=[];this.R=window;this.v=0;this.M=g},jb=function(a,b){this.fn=a;this.win=b};C.prototype.enqueue=function(a,b){this.ba.push(new jb(a,b||this.R));kb(this)};C.prototype.aa=function(a){this.v=1;if(a)this.M=this.R.setTimeout(m(this.N,this),a)};C.prototype.N=function(){if(this.v==1){if(this.M!=g){this.R.clearTimeout(this.M);this.M=g}this.v=0}kb(this)};C.prototype.statusz=function(){return f};p(C.prototype,"nq",C.prototype.enqueue);p(C.prototype,"al",C.prototype.aa);
p(C.prototype,"rl",C.prototype.N);p(C.prototype,"sz",C.prototype.statusz);var kb=function(a){a.R.setTimeout(m(a.ra,a),0)};C.prototype.ra=function(){if(this.v==0&&this.ba.length){var a=this.ba.shift();this.v=2;a.win.setTimeout(m(this.pa,this,a),0);kb(this)}};C.prototype.pa=function(a){this.v=0;a.fn()};var lb,mb,nb,ob,pb,qb,rb,sb=function(){rb=qb=pb=ob=nb=mb=lb=j;var a=ta();if(a)if(a.indexOf("Firefox")!=-1)lb=f;else if(a.indexOf("Camino")!=-1)mb=f;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)nb=f;else if(a.indexOf("iPad")!=-1)ob=f;else if(a.indexOf("Android")!=-1)pb=f;else if(a.indexOf("Chrome")!=-1)qb=f;else if(a.indexOf("Safari")!=-1)rb=f};sb();var tb=!!window.google_async_iframe_id,D=tb&&window.parent||window,ub=function(){if(tb&&!Xa(D)){for(var a="."+v.domain;a.split(".").length>2&&!Xa(D);){v.domain=a=a.substr(a.indexOf(".")+1);D=window.parent}Xa(D)||(D=window)}return D};var E=function(a){this.C=a;this.Z=[];this.Y=0;this.I=[];this.ka=0;this.Q=[];this.ja=j;this.f=this.ga="";this.ia=j},vb=function(a,b,c){var d=a.C[c],e=a.Z;a.C[c]=function(h){if(h&&h.length>0){var i=h.length>1?h[1].url:g;e.push([b,ia(h[0].url),i])}d(h)}},wb=function(a){a.Y++},xb=function(a,b){a.I.push(b)},yb="http://"+fa()+"/pagead/osd.js",zb=function(a){if(!a.ja){Ma(ub());Ka(yb);a.ja=f}},Ab=function(a,b){if(a.Y>0)for(var c=a.C.document.getElementsByTagName("iframe"),d=a.ia?"google_ads_iframe_":"google_ads_frame",
e=0;e<c.length;e++){var h=c.item(e);h.src&&h.name&&h.name.indexOf(d)==0&&b(h,h.src)}},Bb=function(a,b){var c=a.Z;if(c.length>0)for(var d=a.C.document.getElementsByTagName("a"),e=0;e<d.length;e++)for(var h=0;h<c.length;h++)if(d.item(e).href==c[h][1]){var i=d.item(e).parentNode;if(c[h][2])for(var l=i,n=0;n<4;n++){if(l.innerHTML.indexOf(c[h][2])>0){i=l;break}l=l.parentNode}b(i,c[h][0]);c.splice(h,1);break}},Db=function(a,b){for(var c=0;c<a.I.length;c++){var d=a.I[c],e=Cb(d);if(e)(e=a.C.document.getElementById("google_ads_div_"+
e))&&b(e,d)}};E.prototype.W=function(a){Bb(this,a);Db(this,a);Ab(this,a)};E.prototype.setupOsd=function(a,b,c){this.ka=a;this.ga=b;this.f=c};E.prototype.getOsdMode=function(){return this.ka};E.prototype.getEid=function(){return this.ga};E.prototype.getCorrelator=function(){return this.f};E.prototype.X=function(){return this.Z.length+this.Y+this.I.length};E.prototype.setValidOutputTypes=function(a){this.Q=a};
E.prototype.registerAdBlockByType=function(a,b,c){if(this.Q.length>0){for(var d=0;d<this.Q.length;d++)if(this.Q[d]==a){this.ia=c;if(a=="js")vb(this,b,"google_ad_request_done");else if(a=="html")wb(this);else a=="json_html"&&xb(this,b)}zb(this)}};var Cb=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2)return a[1];return""},Eb=function(){var a=ub();a.__google_ad_urls||(a.__google_ad_urls=new E(a));return a.__google_ad_urls};o("Goog_AdSense_getAdAdapterInstance",Eb);
o("Goog_AdSense_OsdAdapter",E);o("Goog_AdSense_OsdAdapter.prototype.numBlocks",E.prototype.X);o("Goog_AdSense_OsdAdapter.prototype.findBlocks",E.prototype.W);o("Goog_AdSense_OsdAdapter.prototype.getOsdMode",E.prototype.getOsdMode);o("Goog_AdSense_OsdAdapter.prototype.getEid",E.prototype.getEid);o("Goog_AdSense_OsdAdapter.prototype.getCorrelator",E.prototype.getCorrelator);o("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",E.prototype.setValidOutputTypes);
o("Goog_AdSense_OsdAdapter.prototype.setupOsd",E.prototype.setupOsd);o("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",E.prototype.registerAdBlockByType);var Fb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Gb={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",
google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Hb={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var F=document,H=navigator,I=window;
function Ib(){var a=F.cookie,b=Math.round((new Date).getTime()/1E3),c=I.google_analytics_domain_name;c=typeof c=="undefined"?Jb("auto"):Jb(c);var d=a.indexOf("__utma="+c+".")>-1,e=a.indexOf("__utmb="+c)>-1,h=a.indexOf("__utmc="+c)>-1,i={},l=!!I&&!!I.gaGlobal;if(d){a=a.split("__utma="+c+".")[1].split(";")[0].split(".");i.sid=e&&h?a[3]+"":l&&I.gaGlobal.sid?I.gaGlobal.sid:b+"";i.vid=a[0]+"."+a[1];i.from_cookie=f}else{i.sid=l&&I.gaGlobal.sid?I.gaGlobal.sid:b+"";i.vid=l&&I.gaGlobal.vid?I.gaGlobal.vid:
(Math.round(Math.random()*2147483647)^Kb()&2147483647)+"."+b;i.from_cookie=j}i.dh=c;i.hid=l&&I.gaGlobal.hid?I.gaGlobal.hid:Math.round(Math.random()*2147483647);return I.gaGlobal=i}
function Kb(){var a=F.cookie?F.cookie:"",b=I.history.length,c,d=[H.appName,H.version,H.language?H.language:H.browserLanguage,H.platform,H.userAgent,H.javaEnabled()?1:0].join("");if(I.screen)d+=I.screen.width+"x"+I.screen.height+I.screen.colorDepth;else if(I.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c.screen.width+"x"+c.screen.height}d+=a;d+=F.referrer?F.referrer:"";for(a=d.length;b>0;)d+=b--^a++;return Lb(d)}
function Lb(a){var b=1,c=0,d;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Jb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=F.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Lb(a.toLowerCase())};function Mb(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=document.domain}Mb.prototype.toString=function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"};function J(){this.w=Nb(this);this.T=j;if(!this.w)this.T=Ob(this)}J.prototype.S="__gads=";J.prototype.D="GoogleAdServingTest=";J.prototype.O=function(a){this.q=a._cookies_[0];if(this.q!=g){this.w=this.q._value_;Pb(this)}};p(J.prototype,"setCookieInfo",J.prototype.O);
var Qb=function(a,b){var c=(new Date).valueOf(),d=new Date;d.setTime(c+b);return d},Rb=function(a){var b=15552E6;a=Qb(a,b);b="ID=12345:T="+b;var c="/",d=document.domain;return new Mb(b,a.valueOf(),c,d)},Sb="http://"+s("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Tb=function(a,b){if(!(a.w||!a.T)){var c="script",d=document.domain;d=Sb+"&client="+x(b)+"&domain="+x(d);document.write("<"+c+' src="'+d+'"></'+c+">")}},Ob=function(a){document.cookie=
a.D+"Good";var b=Ub(a,a.D);if(b=b=="Good"){var c=Qb(a,-1);document.cookie=a.D+"; expires="+c.toGMTString()}return b},Nb=function(a){return a=Ub(a,a.S)},Ub=function(a,b){var c=document.cookie,d=c.indexOf(b),e="";if(d!=-1){d=d+b.length;e=c.indexOf(";",d);if(e==-1)e=c.length;e=c.substring(d,e)}return e},Pb=function(a){if(a.q!=g)if(a.w){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.S+a.w+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;document.cookie=a}};function Vb(a,b){try{return a.top.document==b}catch(c){}return j};var Wb=function(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]};var Xb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Yb=function(a){return a&&decodeURIComponent(a)};var Zb=function(a){this.qa=(this.U=a&&a.GA_jstiming)&&this.U.load};Zb.prototype.tick=function(a,b){this.qa.tick(a,b)};Zb.prototype.report=function(a){var b={};b.e=a;this.U.report(this.qa,b)};var $b=function(){};q($b,Zb);$b.prototype.tick=function(){};$b.prototype.report=function(){};var ac=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var bc=function(a,b){var c=0,d=[];a&&d.push(a);if(b){var e=Wa(b);e&&d.push(e)}if(d.length>0)c=Ua(d.join(":"));return c.toString()};var K=w&&Math.random()<Ya&&w.GA_jstiming&&w.GA_jstiming.load&&w.location.protocol=="http:"?new Zb(w):new $b(w);K.tick("js_load");function L(a){return typeof a=="function"}function cc(a,b){if(typeof a!="string"||a.length==0)return g;else if(typeof b!="string"||b.length==0)return g;return dc(M(),a,b)}o("GA_googleAddSlot",cc);function _GA_googleInitializeAdEngine(a){if(!N()){ec(fc(a));gc(N())}}o("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function hc(){M().sa=f;_GA_googleInitializeAdEngine(g);var a=N().g;a=="sync"||a=="sync_sra"?N().j():ic(M())}o("GA_googleFetchAds",hc);function jc(){_GA_googleInitializeAdEngine("iframe");Tb(window._GA_googleCookieHelper,window.GS_googleGetIdsForAdSenseService())}o("GA_googleUseIframeRendering",jc);function kc(){var a=window.GA_googleEnv.getParameter("google_ad_impl");a==g&&window.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}o("GA_googleUseSyncSRARendering",kc);
function lc(a){window.GA_googleEnv.setParameter("google_domain_reset_url",a)}o("GA_googleDomainResetUrl",lc);function mc(a){var b=Ia(v);nc(M(),a,b);if(N()!=g)if(N().g!="iframe"){if(oc(N()))if(N().P){b=O(M(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(P(N(),a)!=g&&!N().l)return;N().n(a)}}o("GA_googleFillSlot",mc);function pc(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;var e=Ia(v);nc(M(),b,e);if(N()!=g)if(N().g=="iframe"){dc(M(),a,b);a=new qc(c,d,j,f);rc(M(),b,a);N().n(b)}}
o("GA_googleFillSlotWithSize",pc);function sc(){tc(new uc(Fb));ec(g)}o("GA_googleResetAll",sc);window.google_noFetch=j;function vc(){window.google_noFetch=f}o("GA_googleNoFetch",vc);function wc(){window.google_delayFetch=f}o("GA_googleDelayFetch",wc);function qc(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}
qc.prototype.toString=function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"};function xc(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(yc," ")):unescape(d[1]):""}catch(e){}}return b}function zc(a){a=a||document.URL;this.na=xc(a)}
zc.prototype.getParameter=function(a){return a==g?g:this.na[a]};zc.prototype.setParameter=function(a,b){this.na[a]=b};var Ac=function(){if(!fb)return"http://"+s("","pubads.g.doubleclick.net");return"https://"+s("","securepubads.g.doubleclick.net")};function Q(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}function Bc(){this.G=g;this.oa=j;this.Ba=(new Date).valueOf()}
var Dc=function(a,b){if(a.G==g)if(!a.oa){a.G=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.G){var c=a.G.document,d=[];d.push('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');
d.push("<p>Google Ad Capture Window</p>");for(var e in b)L(b[e])||d.push(Cc(a,e,b[e]));d.push("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d.push("<script>displayTime('blocked', pageStartTime);<\/script>");d.push("<p>Total Page Load Time (ms): <label id='total'></label>");d.push("</body>\n</html>");d=d.join("\n");(e=window.GA_googleEnv.getParameter("google_capture_norender")!=g)?c.write(Q(d)):c.write(d);c.close()}else a.oa=f}},Cc=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";
var d="<p>Slot "+b+"</p>";c=c==g||c._html_==g?"No ad":c._html_;var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function Ec(a){this.d={};this.F=a}var Fc=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.F)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Gc=function(a,b){for(var c in b.d)L(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};
Ec.prototype.getAttribute=function(a){return this.d[a]};Ec.prototype.i=function(){var a=[];for(var b in this.d)if(!L(this.d[b])){var c=Fb[b]||Gb[b]||Hb[b]||g,d=this.d[b];c&&d&&a.push(c+"="+x(d))}return a.join("&")};
var Ic=function(a,b,c,d){a=Hc(a,b,c,d);b=[];a[0]&&a[0].length>0&&b.push(a[0].join("&"));a[1]&&a[1].length>0&&b.push("sps="+a[1].join("|"));return b.join("&")},Hc=function(a,b,c,d){var e=[],h=[];b=b.d;for(var i in d)if(!L(i)){var l=d[i];if(l){var n="";if(b[i]!=g)n=x(b[i]);var G=[],z=-1,A=-1;for(var B in a)if(!L(a[B])){++z;if(c[B]==g)G.push("");else{var ea=c[B].d;if(ea[i]!=g){G.push(x(x(ea[i])));A=z}else G.push("")}}if(A>=0){z=x(n);n=[];n.push(z);for(z=0;z<=A;++z)n.push(G[z]);h.push(l+","+n.join(","))}else n&&
e.push(l+"="+n)}}a=[];a.push(e);a.push(h);return a};function Jc(a,b){this.L=a;this.s=b;this.ca=0;this.ya=this.V=this.$=j;this.wa=this.xa=this.ha=this.ta=g}var Kc=function(a){a.V=f;a.ta=(new Date).valueOf()},Lc=function(a){a.ha=(new Date).valueOf()},Mc=function(a){a.ya=f;a.xa=(new Date).valueOf()},Nc=function(a){a.wa=(new Date).valueOf()};Jc.prototype.toString=function(){return"[GA_GoogleAdSlot: pubid="+this.L+", name="+this.s+", loaded="+this.$+", tries="+this.ca+"]"};
function uc(a){this.a={};this.c=[];this.r={};this.F=a;this.ma=new Ec(this.F);this.B={};this.sa=j;this.o=g;this.ea={}}
var dc=function(a,b,c){b=new Jc(b,c);return a.a[b.s]=b},Oc=function(a,b){var c=[];for(var d in a.a)if(!L(a.a[d])){if(b){var e=O(a,d);if(e==g||!e._enabled_)continue}e=a.a[d];e.V||c.push(e)}return c},Pc=function(a,b){return Oc(a,b).length},Qc=function(a){var b=[];for(var c in a.a){var d=a.a[c];L(d)||d.V&&d.ha==g&&b.push(c)}return b},Rc=function(a){var b=0;for(var c in a.a)if(!L(a.a[c])){var d=O(a,c);d!=g&&d._enabled_&&b++}return b},Sc=function(a){for(var b in a.a)if(!L(a.a[b])){var c=a.a[b];Kc(c)}},
Tc=function(a,b){var c=a.a[b];Kc(c)},Uc=function(a,b){var c=a.a[b];Lc(c)},Vc=function(a,b){var c=a.a[b];Mc(c)},R=function(a,b){var c=a.a[b];Nc(c);ac(K,"ga_render",a.c.length,"ga_srt")},Wc=function(a){var b=0;for(var c in a.a)L(a.a[c])||b++;return b};uc.prototype.toString=function(){var a="[AdData:",b=[];for(var c in this.a)L(this.a[c])||b.push(this.a[c].toString());for(var d in this.r)L(this.r[d])||b.push("["+d+","+this.r[d]+"]");a+=b.join();a+="]";return a};
var S=function(a,b){return a.a[b]},Xc=function(a,b,c){if(!(b==g||b.length==0)){if(c==g||c.length==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function Yc(a,b){Xc(M(),a,b)}o("GA_googleAddAttr",Yc);var Zc=function(a,b,c){Fc(a.ma,b,c)};function $c(a,b){Zc(M(),a,b)}o("GA_googleAddAdSensePageAttr",$c);var ad=function(a){return a.ma},bd=function(a,b,c,d){if(!(b==g||b.length==0)){if(N()==g||N().g!="iframe"){var e=a.a[b];if(e==g)return}e=a.B[b];if(e==g)a.B[b]=new Ec(a.F);Fc(a.B[b],c,d)}};
function cd(a,b,c){bd(M(),a,b,c)}o("GA_googleAddAdSenseSlotAttr",cd);
var dd=function(a,b){return a.B[b]},nc=function(a,b,c){a.ea[b]=c},ed=function(a,b){return a.ea[b]},fd=function(){var a=Ac();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},ic=function(a){if(a.o!=g)N().j();else{var b=[];for(var c in a.a)L(a.a[c])||b.push(c);a=window.GS_googleGetIdsForAdSenseService();b=fd(window)+"&client="+escape(a)+"&page_slots="+escape(b.join());document.write("<script src = '"+b+"'><\/script>")}},gd=function(a,b){a.o=b;N().P=f;N().j()};
function hd(a){gd(M(),a)}o("GA_googleSetAdSlotAttributes",hd);var rc=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;N().P=f},O=function(a,b){return a.o!=g?a.o[b]:g};function id(a,b,c){if(!c||c<0||c>1)c=0;this.za=Math.random()<c;this.ua=a;this.da=b+"/pagead/gen_204?id="+x(a);this.va=[]}
var T=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.da+="&"+b+"="+x(c)},jd=function(a){var b=M();for(var c in b.a){var d=b.a[c];if(!L(d)&&d.L!=g){T(a,"pub_id",d.L);break}}T(a,"nslots",Wc(b).toString());T(a,"pub_url",document.URL);T(a,"pub_ref",document.referrer)},kd=function(a){if(!a.za||!a.ua||!a.da)return j;var b=new Image;b.src=a.da;a.va.push(b);return f};function U(a){this.h=g;this.o={};this.p=this.b="";this.l=a;this.m=this.K=this.t=j;this.g="sync";this.Aa=Fb;this.u=f;this.fa=this.P=j}
var gc=function(a){a.t=window.GA_googleEnv.getParameter("google_nofetch")!=g||window.google_noFetch;a.K=window.GA_googleEnv.getParameter("google_norender")!=g;a.m=window.GA_googleEnv.getParameter("google_capture")!=g||window.GA_googleEnv.getParameter("google_capture_norender")!=g;if(a.m)a.K=f;ld(a,window);a.b=a.p;var b=m(a.la,a);md(a,window,b)},nd=function(a){a.fa=f},md=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,j);return f}return j};
U.prototype.H=function(){this.m&&Dc(window.GA_googleAdCapture,this.h)};var od=function(a){if(a.g=="sync_sra"){var b=M(),c=Wc(b);b=b.c.length;if(c!=b){a.J=new id("sra_mismatch",Ac(),$a);T(a.J,"correlator",a.f);T(a.J,"fslots",b.toString());jd(a.J);kd(a.J)}}},pd=function(a){K.tick("ga_onload");K.report(a.g)},qd=function(a){var b=Qc(M());if(b.length>0){a.A=new id("missing_cb",Ac(),Za);T(a.A,"pending",b.join());T(a.A,"correlator",a.f);T(a.A,"impl",a.g);jd(a.A);kd(a.A)}};
U.prototype.la=function(){pd(this);this.H();od(this);qd(this)};var ld=function(a){var b=window.GA_googleEnv.getParameter("google_ad_url");if(b==g||b.length==0)a.p=Ac()+"/gampad/ads?";else{if(b.charAt(b.length-1)!="?")b+="?";a.p=b}};U.prototype.k=function(){};
var P=function(a,b){return a.h!=g?a.h[b]:g},rd=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");return b==-1?0:parseFloat(a.substring(b+5,a.indexOf(";",b)))},yc=/\+/g,sd=function(a,b){b=b.toLowerCase();if(b.substring(0,3)!="ca-")b="ca-"+b;return b},W=function(a,b,c){c!=g&&V(a,b,x(c.toString()))},V=function(a,b,c){if(c!=g&&c!="")a.b+=a.b.charAt(a.b.length-1)!="?"?"&"+b+"="+c:b+"="+c},td=function(a,b){for(var c=Oc(M(),a.u),d=[],e=[],h=[],i=c.length,l=0;l<i;l++){var n=c[l];h.push(n.s);if(!(b!=
g&&b!=n.s)){d.push(n.s);e.push(sd(a,n.L))}}W(a,"client",e[0]);if(a.l)h.length>0&&W(a,"page_slots",h.join());else{W(a,"slotname",d.join());M().c.length>0&&W(a,"page_slots",M().c.join())}},ud=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b.indexOf("google_preview=",a);c=b.indexOf("&",a);if(c==-1){c=b.length-1;a-=1}return b.substring(0,a)+b.substring(c+1,b.length)}return b},vd=function(a,b,c){if(Vb(b,c))return c.URL;return c.referrer},xd=function(a,b,c){if(wd(a,b,c)!=c.URL)return c.domain;return""},
wd=function(a,b,c){var d=ad(M()).getAttribute("google_page_url");if(d)return d;return vd(a,b,c)},yd=function(a,b,c,d){W(a,"url",ud(a,wd(a,window,document),window.GA_googleEnv.getParameter("google_preview")));W(a,"ref",document.referrer);W(a,"lmt",(Date.parse(document.lastModified)/1E3).toString());V(a,"dt",b.getTime());if(document.body){b=document.body.scrollHeight;var e=document.body.clientHeight;e&&b&&W(a,"cc",Math.round(e*100/b).toString())}b=f;if(b=Ta(b)){W(a,"biw",b.width);W(a,"bih",b.height)}b=
Wb(window);W(a,"ifi",b);b=Va(window);b!=0&&W(a,"ifk",b.toString());b=bc(c,ed(M(),c));W(a,"adk",b);b=window.GA_googleEnv.getParameter("deb");b!=g&&W(a,"deb",b);b=window.GA_googleEnv.getParameter("haonly");b!=g&&W(a,"haonly",b);b=ad(M());navigator.userAgent.indexOf("MSIE ")>0&&Fc(b,"google_encoding",document.charset,j);e="";if(d)e=Ic(M().a,b,M().B,a.Aa);else{c=dd(M(),c);if(c==g)c=b;else Gc(c,b);e=c.i()}if(e)a.b+="&"+e},zd=function(a,b,c){var d=M().r,e=[];for(var h in d)L(d[h])||e.push(x(h)+"="+x(d[h]));
W(a,"cust_params",e.join("&"));if(b._GA_googleCookieHelper){W(a,"cookie",b._GA_googleCookieHelper.w);b._GA_googleCookieHelper.T&&W(a,"cookie_enabled","1")}(b=xd(a,b,c))&&W(a,"cdm",b)},Ad=function(a){Ib();var b=window;V(a,"ga_vid",b.gaGlobal.vid);V(a,"ga_sid",b.gaGlobal.sid);V(a,"ga_hid",b.gaGlobal.hid);V(a,"ga_fc",b.gaGlobal.from_cookie);W(a,"ga_wpids",b.google_analytics_uacct)},Bd=function(a,b){for(var c in b){var d=b[c];L(d)||V(a,c,d)}},Dd=function(a){var b=[];if(ba(window.GS_googleGetExpIdsForAdSense)==
"function"){var c=window.GS_googleGetExpIdsForAdSense();c&&b.push(c)}(c=Cd(a.f.toString()))&&b.push(c);b.length>0&&W(a,"eid",b.join())};
U.prototype.i=function(a){this.k();Dd(this);var b=new Date;td(this,a);zd(this,window,document);window.GA_googleEnv.getParameter("google_preview")!=g&&V(this,"gct",window.GA_googleEnv.getParameter("google_preview"));Ad(this);yd(this,b,a,this.l);a={};Sa(a);Bd(this,a);V(this,"flash",Qa());this.b=this.b.substring(0,2E3);this.b=this.b.replace(/%\w?$/,"");if(this.fa){a=this.g=="iframe"||this.g=="fallback"?"html":"json_html";Eb().registerAdBlockByType(a,this.b,f)}return this.b};
var oc=function(a){return a.u},Ed=function(a,b){var c=b.getAttribute("id");return c=c.substr(18,c.length-18)},Fd=function(a,b,c,d){a='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:block;">'+d+"</ins>";return b='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:inline-table;">'+a+"</ins>"},Gd=function(a,b,c,d,e,h){var i="google_ads_iframe_"+b,l=[];b="google_ads_div_"+b;var n="border:0px;left:0;position:absolute;top:0;";l.push("<iframe id=",
i," name=",i,' width="',e,'" height="',h,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.m?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" ','style="',n,'"',' src="',Q(c),'"');d!=g&&l.push(' onload="',d,'"');l.push("></iframe>");c=[];l=l.join("");c.push("<div id=",b,">");c.push(Fd(a,e,h,l));c.push("</div>");a=c.join("");document.write(a)},Hd=function(a,b,c){var d=P(a,c),e=d._width_,h=d._height_;d=d._html_;var i=document.createElement("iframe");i.id="google_ads_iframe_"+
c;i.name="google_ads_iframe_"+c;i.width=e;i.height=h;i.vspace=0;i.hspace=0;i.allowTransparency="true";i.scrolling="no";i.marginWidth=0;i.marginHeight=0;i.frameBorder=0;i.style.border=0;b=document.getElementById(b);i.style.position="absolute";i.style.top=0;i.style.left=0;var l=document.createElement("ins");l.style.width=e+"px";l.style.height=h+"px";l.style.border=0;l.style.display="block";l.style.position="relative";var n=document.createElement("ins");n.style.width=e+"px";n.style.height=h+"px";n.style.border=
0;n.style.display="inline-table";n.style.position="relative";l.appendChild(i);n.appendChild(l);b.appendChild(n);if(a.m){i.contentWindow.document.write(Q(d));i.scrolling="auto"}else i.contentWindow.document.write(d);i.contentWindow.document.write("<script>document.close();<\/script>");R(M(),c)};function Id(a,b){Hd(N(),a,b)}o("GA_googleCreateDomIframe",Id);
var Jd=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=0,d=b.length;c<d;++c){var e=b[c],h=e.getAttribute("target");if(h){a.push({baseElement:e,originalTagValue:h});e.removeAttribute("target")}}return a},Kd=function(a){if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Ld=function(a){var b="http://"+fa()+"/pagead/inject_object_div.js";if(parseInt(rd(),10)>6)return j;if(a.indexOf(b)<0)return j;return f},Md=function(a,
b,c){if(a.m)c=Q(c);a=Jd();window.frames[b.name].contents=c;b.src=Ld(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Kd(a)},Nd=function(a,b,c){var d=Ed(a,b);try{var e=b.contentWindow?b.contentWindow.document:b.contentDocument;if(e==g)if(document.implementation&&document.implementation.createDocument)e=document.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return j;e.open("text/html",
"replace");a.m?e.write(Q(c)):e.write(c);e.close()}catch(h){return j}return f},Od=function(a,b){var c=Ed(a,b),d=S(M(),c);if(!d.$){d.$=f;d=P(a,c);var e=b.parentNode;if(d==g||d._html_==g)e.removeChild(b);else if(d._expandable_&&!(d._is_afc_&&d._is_3pas_))e.innerHTML=d._html_;else d._is_3pas_?Md(a,b,d._html_):Nd(a,b,d._html_);R(M(),c)}},Pd=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";var d=P(a,b);if(d!=g){c+=d._html_;c+="\n</div>\n";document.write(c);R(M(),b)}},Qd=function(a,b){var c="google_ads_div_"+
b,d="<div id="+c+">";d+="\n</div>\n";document.write(d);return c},Rd=function(a){if(!a.u)return f;if(Pc(M(),a.u)>0)return f;else if(Rc(M())==0)return j},Sd=function(a,b){ac(K,"ga_srt",M().c.length,"_ga_start");if(a.h==g){a.h=b;for(var c in b)L(b[c])||Uc(M(),c)}else for(c in b)if(!L(b[c])){a.h[c]=b[c];Uc(M(),c)}var d=j;for(c in b)if(!L(b[c])){var e=b[c];if(d){e._cookies_=[Rb(window._GA_googleCookieHelper)];d=j}e!=g&&e._cookies_!=g&&window._GA_googleCookieHelper.O(e)}};function Td(a){Sd(N(),a)}
o("GA_googleSetAdContentsBySlot",Td);function X(a){U.call(this,a);this.u=j;this.f=(new Date).getTime();this.g=a?"sync_sra":"sync"}q(X,U);X.prototype.k=function(){this.b=this.p;W(this,"correlator",this.f.toString());V(this,"output","json_html");V(this,"callback","GA_googleSetAdContentsBySlotForSync");this.l?V(this,"impl","ss"):V(this,"impl","s");Ud(this,M().c);if(!this.l){Vd(this,M().c,this.h);Wd(this,M().c,this.h)}};
var Ud=function(a,b){for(var c=0,d=f,e=0;e<b.length;++e){var h=a.h&&a.h[b[e]];if(h)if(h._is_afc_==undefined){d=j;break}else c=2*c+(h._is_afc_?1:0)}d&&V(a,"prev_afc",c)},Wd=function(a,b,c){if(b&&c){var d=b.length-2;if(d>=0){b=b[d];(c=c[b])&&c._pstok_&&W(a,"pstok",c._pstok_)}}},Vd=function(a,b,c){if(b&&c){for(var d=[],e=[],h=b.length-1,i=0;i<h;i++){var l=b[i];if((l=c[l])&&l._cids_&&l._a2ids_){d.push(l._cids_[0]);e.push(l._a2ids_[0])}else{d.push("");e.push("")}}if(d.length>0){b=d.join(",");e=e.join(",");
W(a,"a2ids",e);W(a,"cids",b)}}},Xd=function(a,b){var c=M().a;c=c[b];if(c!=g)if(!a.t){a.i(c.s);Tc(M(),b);document.write("<script src = '"+a.b+"'><\/script>")}},Zd=function(a,b){Sd(a,b);if(a.l)if(M().c.length==1){var c=M().c[0];Yd(a,c);return}for(c in b)L(b[c])||Yd(a,c)};function $d(a){Zd(N(),a)}o("GA_googleSetAdContentsBySlotForSync",$d);X.prototype.j=function(){Rd(this)};var ae=function(a){a.i(g);document.write("<script src = '"+a.b+"'><\/script>");Sc(M())};
X.prototype.n=function(a){M().c.push(a);ac(K,"_ga_start",M().c.length);if(this.l)M().c.length==1?ae(this):Yd(this,a);else Xd(this,a)};
var be=function(a,b,c){if(b.google_js_backfill){a="script";c.write("<"+a+' src="'+Ja+'"></'+a+">")}},Yd=function(a,b){ce(a,window,document,b)},ce=function(a,b,c,d){var e=S(M(),d);if(e!=g){e=P(a,d);Vc(M(),d);if(e==g||e._empty_){be(a,b,c,d);R(M(),d)}else if(a.K&&!a.m)R(M(),d);else if(e._snippet_&&!e._is_afc_&&!a.m)Pd(a,d);else if(b.navigator.userAgent.indexOf("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var h="about:blank";if(b=b.GA_googleEnv.getParameter("google_domain_reset_url")){var i=Yb(b.match(Xb)[3]||
g);if(i===g||i.indexOf(document.domain)>=0)h=b}Gd(a,d,h,c,e._width_,e._height_)}else{a=Qd(a,d);c.write("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},de=function(a,b){var c=Ed(a,b);S(M(),c);Od(a,b)};function ee(a){de(N(),a)}o("GA_googleSyncAdSlotLoaded",ee);function Y(a){U.call(this,a);this.f=(new Date).getTime();this.g="async"}q(Y,U);
Y.prototype.k=function(){this.b=this.p;fe(this);W(this,"correlator",this.f.toString());V(this,"output","json_html");V(this,"callback","GA_googleSetAdContentsBySlot");V(this,"impl","a")};var fe=function(a){a.delay=500;var b=window.GA_googleEnv.getParameter("google_async_delay");if(b!=g)a.delay=1E3*b};Y.prototype.j=function(){if(Rd(this))this.t||window.setTimeout("GA_googleReallyFetchAds();",20)};
var ge=function(a){if(Pc(M(),a.u)!=0){var b=document.getElementsByTagName("head")[0];if(a.l){var c=document.createElement("script");c.src=a.i(g);b.appendChild(c);Sc(M())}else{var d=M().a;for(var e in d)if(!L(d[e])){c=document.createElement("script");c.src=a.i(e);b.appendChild(c);Tc(M(),e)}}}};function he(){ge(N())}o("GA_googleReallyFetchAds",he);
Y.prototype.n=function(a){var b=S(M(),a);if(b!=g){M().c.push(a);b="GA_googleAsyncAdSlotLoaded(this);";var c=O(M(),a);Gd(this,a,"about:blank",b,c._width_,c._height_)}};var je=function(a,b){var c=Ed(a,b);S(M(),c);!a.t&&!a.K&&ie(a,b)};function ke(a){je(N(),a)}o("GA_googleAsyncAdSlotLoaded",ke);var ie=function(a,b){var c=Ed(a,b),d=S(M(),c);if(a.h==g||a.h[c]==g){if(!(d.ca>30)){window.setTimeout(function(){ie(N(),b)},a.delay);d.ca++}}else Od(a,b)};Y.prototype.H=function(){};
function Z(a){U.call(this,a);this.f=(new Date).getTime();this.g="fallback"}q(Z,U);Z.prototype.k=function(){this.b=this.p;W(this,"correlator",this.f.toString());V(this,"output","html");V(this,"impl","fb")};Z.prototype.j=function(){Rd(this)};Z.prototype.z=function(a){if(this.l){this.i(g);a=this.b+"&currentslot="+x(a)}else a=this.i(a);return a};Z.prototype.n=function(a){var b=O(M(),a);if(b!=g){M().c.push(a);if(!this.t){var c=this.z(a);Gd(this,a,c,g,b._width_,b._height_)}}};
function $(a){U.call(this,a);this.f=(new Date).getTime();this.P=f;this.g="iframe"}q($,U);$.prototype.k=function(){this.b=this.p;W(this,"correlator",this.f.toString());V(this,"output","html");V(this,"impl","ifr")};$.prototype.j=function(){Rd(this)};$.prototype.z=function(a){if(this.l){this.i(g);a=this.b+"&currentslot="+x(a)}else a=this.i(a);return a};$.prototype.n=function(a){var b=O(M(),a);if(b!=g){M().c.push(a);if(!this.t){var c=this.z(a);Gd(this,a,c,g,b._width_,b._height_)}}};
var le=function(){if(Pa()){var a=rd();return a<=5}else if(y("firefox")){var b=navigator.userAgent.indexOf("Firefox")+8;a=parseInt(navigator.userAgent.charAt(b),10);b=navigator.userAgent.slice(b);return a<1}else if(y("safari")){b=navigator.userAgent.indexOf("Safari")+7;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<412}else if(window.opera!=g){b=navigator.userAgent.indexOf("Opera")+6;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<9}else if(!Pa()&&!y("safari")&&y("mozilla")){b=navigator.userAgent.indexOf("Netscape")+
9;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<7}else return f},me=function(){if(Pa()){var a=rd();return a>5}else if(y("firefox")){a=navigator.userAgent.indexOf("Firefox")+8;var b=parseInt(navigator.userAgent.charAt(a),10);navigator.userAgent.slice(a);return b>1}return j},ne=function(){if(le())return"fallback";else if(window.google_delayFetch&&me())return"async";return"sync"},fc=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=window.GA_googleEnv.getParameter("google_ad_impl");
if(b==g)b=ne()}switch(b){case "async":return new Y(j);case "sync":return new X(j);case "sync_sra":return new X(f);case "fallback":return new Z(j);case "iframe":return new $(j);default:return new Z(j)}},oe;function M(){oe||(oe=new uc(Fb));return oe}function tc(a){delete oe;oe=a}var pe;function N(){pe||(pe=g);return pe}function ec(a){delete pe;pe=a}if(typeof window.GA_googleEnv=="undefined")window.GA_googleEnv=new zc;if(typeof window.GA_googleAdCapture=="undefined")window.GA_googleAdCapture=new Bc;
if(window._GA_googleCookieHelper==g)window._GA_googleCookieHelper=new J(g);function Cd(a){var b=Eb(),c=b.getEid();if(c==""){if(c=qe(window)){var d=b.getOsdMode();if(c=="36815006"||c=="36813008"){b.setValidOutputTypes(["html","json_html"]);d=c=="36815006"?1:0}b.setupOsd(d,c,a);(a=N())&&nd(a)}}else if(c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007")c="";return c}
function qe(a){if((a.google_unique_id||0)!=0)return"";a=Ra(["36815005","36815006"],ab);if(a=="")a=Ra(["36813007","36813008"],bb);return a}K.tick("js_parse","js_load");K.tick("jl");})()
