#!/bin/bash
GN_COMPILE_TOOLS_PATH="gionee/config"

ota_oldfilelist=ota_oldfilelist.txt
ota_newfilelist=ota_newfilelist.txt
ls ../ota_old_tmpfiles > $ota_oldfilelist
ls ../ota_new_tmpfiles > $ota_newfilelist
while read oldtmpline
do
	while read newtmpline
	do
		#echo "$1"
		#echo "$oldtmpline $newtmpline"
		echo "./${GN_COMPILE_TOOLS_PATH}/tools/gn_make_inc_pkg $1 $oldtmpline $newtmpline"
		./${GN_COMPILE_TOOLS_PATH}/tools/gn_make_inc_pkg $1 ../ota_old_tmpfiles/$oldtmpline ../ota_new_tmpfiles/$newtmpline
	done < $ota_newfilelist
done < $ota_oldfilelist

ota_md5filelist=ota_md5filelist.txt
ls ../ota > $ota_md5filelist
rm -rf ../ota/check.md5
while read md5tmpline
do
	if [[ $md5tmpline = "check.md5" ]];then
		echo "check.md5"
	else
		./${GN_COMPILE_TOOLS_PATH}/tools/gn_make_md5 ../ota/$md5tmpline >> ../ota/check.md5
	fi
done < $ota_md5filelist

mv ../ota_new_tmpfiles/* ../ota_old_tmpfiles/

rm -rf $ota_oldfilelist
rm -rf $ota_newfilelist
rm -rf $ota_md5filelist
